version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nproxyadmin"
      DB_MYSQL_PASSWORD: "nproxypassword"
      DB_MYSQL_NAME: "nproxy"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'nproxy'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./data/mysql:/var/lib/mysql