version: '3'

services: 
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - app-network
    depends_on:
    - "mongo-express"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports: 
      - 8080:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - app-network

  fast-api-server:
    build: fastapi/
    ports: 
      - 8080:8082
    networks:
      - app-network
    container_name: auth_server

networks:
  app-network:
    driver: bridge