version: '3'

services: 
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - my-app-network
    depends_on:
    - "mongo-express"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - my-app-network

  fastapi:
    image: fastapi
    ports: 
      - 8082:8082
    depends_on:
    - "mongodb"
    networks:
      - my-app-network
    container_name: fastapi
    volumes:
      - ./fastapi:/app

  streamlit:
    image: streamlit
    depends_on:
      - fastapi
    ports: 
        - 8504:8504
    networks:
      - my-app-network
    container_name: streamlit

networks:
  my-app-network:
    driver: bridge